### ISSUE TITLE
Consider adding function to retrieve file paths to the template

### ISSUE THREAD

**Issue by nrueh** [potassco/python-project-template#43]
The following script can be used to safely retrieve file paths of (non-python) files inside the project.

```
import atexit
from contextlib import ExitStack

import importlib_resources


def get_file_path(package: str, file_name: str) -> str:
    """Gets the path for a file

    Args:
        package (str): The package, for instance "fillname.encodings"
        file_name (str): The name of the file with the extension

    Returns:
        str: The string for the path to the file
    """
    file_manager = ExitStack()
    atexit.register(file_manager.close)
    ref = importlib_resources.files(package)
    file = file_manager.enter_context(importlib_resources.as_file(ref / file_name))
    return str(file)
```

**Comment by nrueh** [comment]
From Python 3.7 the library `importlib.resources` is also integrated into Python, however, I got an error when running the tests with `nox` and Python 3.9 (with 3.12 it worked fine).

```
ImportError: Failed to import test module: tests.test_main
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/coom-solver/coom-solver/tests/test_main.py", line 8, in <module>
    from coomsolver.utils import logging
  File "/home/runner/work/coom-solver/coom-solver/.nox/test-3-9/lib/python3.9/site-packages/coomsolver/__init__.py", line 19, in <module>
    ENCODING = get_file_path("coomsolver.encodings", "encoding-kids.lp")
  File "/home/runner/work/coom-solver/coom-solver/.nox/test-3-9/lib/python3.9/site-packages/coomsolver/utils/__init__.py", line 22, in get_file_path
    ref = resources.files(package)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/importlib/resources.py", line 147, in files
    return _common.from_package(_get_package(package))
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/importlib/_common.py", line 14, in from_package
    return fallback_resources(package.__spec__)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/importlib/_common.py", line 18, in fallback_resources
    package_directory = pathlib.Path(spec.origin).parent
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by rkaminsk** [comment]
This looks super complicated. Do we really need that? We should also spend some time to see why it does not work with the inbuilt library instead using an external library (even though it is just a newer version as compared to the inbuilt one).

I just skimmed the docs a bit and would expect that this can also be written like:
```python
with as_file(files(package) / file_name) as hnd:
    return str(file)
```

The `ExitStack` is designed to work with multiple context managers. Here we have just one, so the with statement is just fine.

**Comment by nrueh** [comment]
So you are saying not to include it at all or to include the simpler version?

I just tested this and it works, although, there was a small mistake:
```
with as_file(files(package) / file_name) as file:
    return str(file)
```

I could not really find anything about why it fails. It seems to have to do with pathlib but this is also inbuilt...

**Comment by rkaminsk** [comment]
Since it is all python code, it should be possible to debug this. Could you prepare a minimal working example to reproduce the problem. Then we could have a look.

**Comment by nrueh** [comment]
This should do it. I tested it locally now only with Python 3.9 (error) and 3.12 (no error).
```
import os
from importlib.resources import as_file, files

dir = "test_module"
if not os.path.exists(dir):
        os.makedirs(dir)
with as_file(files(dir) / "file_name") as file:
    print(str(file))
```

**Comment by rkaminsk** [comment]
> This should do it. I tested it locally now only with Python 3.9 (error) and 3.12 (no error).
> 
> ```
> import os
> from importlib.resources import as_file, files
> 
> dir = "test_module"
> if not os.path.exists(dir):
>     os.makedirs(dir)
> with as_file(files(dir) / "file_name") as file:
>     print(str(file))
> ```

I am not sure this is enough. Is this supposed to work with modules that have not been installed? Maybe it is also due to problems with editable installs as done by our noxfile. I'll try to have a closer look next week. Have a nice weekend.

**Comment by nrueh** [comment]
Thanks! I tested this locally in the terminal and it threw the error so I think it does not have anything to do with those things. The module can apparently just be an empty folder.

**Comment by rkaminsk** [comment]
I checked and the library seems to be working as expected with python 3.9. I also understand the complicated at exit construction now and would still recommend to only do this if absolutely necessary. I experimented with this project.

The code below opens the file as expected (installed using `pip install -e .` and `pip install .`):
```python
with as_file(files("fillname") / "test.txt") as path:
    with open(path, 'r') as hnd:
        print(hnd.read())
````

So getting the contents of a file is simple and depending on how you want to use the file something more complicated is required. I don't see a need to provide anything in the project template because the functionality is directly available.

I would not use `at_exit`. If you need the files just store the `ExitManager` somewhere and close it yourself (best using the with statement).

**Comment by rkaminsk** [comment]
I tried to reproduce the error with python 3.9 and I cannot. Your short example above fails but I would say that this is to be expected. You need a (possibly empty) `__init__.py` in the folder to turn it into a package. If you add it, it works as expected. Do you have an `__init__.py` in your tests folder?

In my tests a call to your function:

          print(get_file_path("tests", "test.txt"))

or the code:

          with as_file(files("tests") / "test.txt") as hnd:
              print(hnd)

produce the desired results.

Note that for the tests it is fine to let the context manager exit scope and still use the path. As the tests won't be installed, no extracting of files is required; the returned path should always be an absolute path to the file in the source directory. Of course one can simply write the one additional line to always be on the safe side.

I'd like to close this as invalid. Any opinions?

**Comment by nrueh** [comment]
There is no `__init__.py` in my folder. I created a new folder and only added the above script and it failed.
 I am on macOS, maybe something works different because of that?

For the rest I agree that this does not need to be added if it can be expressed in such a simple way, so go ahead and close it from my side.

**Comment by rkaminsk** [comment]
Okay, just one last note. You should not even have to add an `__init__.py` file to the encodings folder. I think that

```python
with as_file(files("test_module") / "encodings" / "test.txt") as path:
    print(path)
```

should work.

**Comment by rkaminsk** [comment]
> ```python
> with as_file(files("test_module") / "encodings" / "test.txt") as path:
>     print(path)
> ```

Just make sure to put the encodings folder into the `test_module` folder. (I think that any `package_data` should go into the module folder that is using the data.)
